### ISSUE TITLE
Prevent images (& the like) from being injected

### ISSUE THREAD

**Issue by Gingerdude** [greenpeace/planet4-gpnordic-plugin-leads#17]
**The situation**
The consent message has an `Add Media` button, which allows for adding of pictures. Pictures can easily be copied in to other WYSIWYG fields. At least the `Consent Message` and `Form Description` are allowing it to show on the front-end.

**Questions to answer before acting**
- Since the fields were switched to WYSIWYG later in the process, and clearly not fully tested: **Which fields** are able to inject undesired content into the front-end?
-  Should some of the fields simply **not allow** for the styling of text? _(fields were switched to WYSIWYG to allow for multi-line texts, but some fields may not even need this 'luxury')_
- Which exact list of **elements** do we want **to allow**? _(e.g. `<b>,` `<p>`, `<em>`, `<i>`; using a regex replace to filter out anything else?)_ 
 
**Notes**
1. The solution to this may be similar to that of #13.
2. heroDescription, actually already contains `strip_tags($hero_description)`([leads-form.php](https://github.com/greenpeace/planet4-gpnordic-plugin-leads/blob/373b29dd2753ecf702a9703573e6b6683406a992/templates/blocks/leads-form/leads-form.php), line 419)

**Comment by Gingerdude** [comment]
We may want to make our own `toolbar` for ACF and limit the buttons to `bold`, `italic`, and `link`. For [reference.](https://www.advancedcustomfields.com/resources/customize-the-wysiwyg-toolbars/)

**Comment by Gingerdude** [comment]
Psst, @elncetoo, did we consider the questions and suggestions listed above before closing? Should we create a new issue for the custom toolbar?
>We may want to make our own `toolbar` for ACF and limit the buttons to `bold`, `italic`, and `link`. For [reference.](https://www.advancedcustomfields.com/resources/customize-the-wysiwyg-toolbars/)

**Comment by elncetoo** [comment]
psst @Gingerdude, you fixed that, remember? ;)

**Comment by Gingerdude** [comment]
@elncetoo Right! But partially! We may still want the custom toolbar later; to not allow lists and such. I'll create a new issue for it, let's revisit it when we've fully switched and have more insight into 'editor behavior' 👍

**Comment by elncetoo** [comment]
Sounds like a good plan 👍
