### ISSUE TITLE
Leads plugin adds 2 additional side nav items >> Options, Custom fields

### ISSUE THREAD

**Issue by elncetoo** [greenpeace/planet4-gpnordic-plugin-leads#24]
Those are not in use so needs to be  hidden

**Comment by Gingerdude** [comment]
Likely found in [options.php](https://github.com/greenpeace/planet4-gpnordic-plugin-leads/blob/develop/lib/options.php) and [admin.php](https://github.com/greenpeace/planet4-gpnordic-plugin-leads/blob/a6774e05a502bc46500fe8d7952ec9fbd1f6e8d9/includes/acf/includes/admin/admin.php#L48-L50) respectively.
